config/routes.rb
Rails.application.routes.draw do
  get 'movies/search'
  root 'movies#search'
  
  resources :movies

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/research.rb
class Research < ApplicationRecord
	validates :movie, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def search
  	@tab = nil
  	@research = params[:movie]
  	@tab = SearchMovie.new(@research).perform
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie</title>

    	<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/movies/search.html.erb
<div align="center">
<h1>Quels films recherches tu ?</h1>

<%= form_tag(movies_search_path, method: 'get') do |f| %>
  <%= label_tag 'Saisie ton titre :' %>
  <%= text_field_tag :movie %>
  <%= submit_tag "Go !" %>
<% end %>

<% unless @tab == nil%>
<h1>Voici les films qui correspondent à ta recherche :)</h1>

	<table class="table table-striped">
  	<tr>
  	  <th scope="col" style="text-align: center">Titre du film  </th>
   	  <th scope="col" style="text-align: center">Année de sortie  </th>
   	  <th scope="col" style="text-align: center">Affiche du film  </th>

   
  	</tr>
 
  	<% @tab.each do |film| %>
  
    <tr>
	  <td style="text-align: center"><%= film["title"] %></td>
      <td style="text-align: center"><%= film["release_date"] %></td>
      <td style="text-align: center"><img src="http://cf2.imgobject.com/t/p/w500/<%=film["poster_path"]%>" style="width:150px;"></td>

      
    </tr>
    <% end %>
    </table>
</br>
<% end %>

</div>